databases:
  - name: aise-chatroom-db
    plan: free

services:
  - type: web
    name: aise-chatroom
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aise-chatroom-db
          property: connectionString
